const CONFIG = {
  NOME_PLANILHA: "Financeiro_Pessoal",
  ABA_LANCAMENTOS: "LANÇAMENTOS",
  PASTA_RAIZ: "Financeiro",
  LABEL_ENTRADA: "FINANCEIRO/ENTRADA",
  LABEL_PROCESSADO: "FINANCEIRO/PROCESSADO"
};